language: python

python:
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get install redis-server
  - sudo service redis-server start
  - redis-server --version
  - which redis-server
  - /bin/sleep 10

install:
  - "pip install . --use-mirrors"

before_script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/redis-unix.pid --make-pidfile --background --exec `which redis-server` --  --unixsocket /tmp/asyncio

script: ./tests.py

env:
  matrix:
  - "REDIS_PORT=6379"
  - "START_REDIS_SERVER=True REDIS_PORT=0 REDIS_HOST=/tmp/asyncio"
